version: '2'

services:

 db:
  container_name: ld-postgres
  image: postgres:15.8
  ports:
   - 5432:5432
  environment:
   - POSTGRES_DB=logicaldoc
   - POSTGRES_USER=ldoc
   - POSTGRES_PASSWORD=changeme

 logicaldoc:
  container_name: logicaldoc
  image: logicaldoc/logicaldoc:8.8
  depends_on:
   - db
  command: ["/wait-for-it.sh", "ld-postgres:5432", "-t", "30", "--", "/LogicalDOC/logicaldoc.sh", "start"]
  ports:
   - 8080:8080
  environment:
   - LDOC_MEMORY=3000
   - LDOC_USERNO=
   - DB_HOST=ld-postgres
   - DB_NAME=logicaldoc
   - DB_USER=ldoc
   - DB_PASSWORD=changeme
   - DB_PORT=5432
   - DB_ENGINE=postgres
  volumes:
   - ldoc_conf:/LogicalDOC/conf
   - ldoc_repository:/LogicalDOC/repository

volumes:
  ldoc_db:
  ldoc_conf:
  ldoc_repository:      


