version: '2'
services:
 db:
  container_name: mysql-ld
  image: mysql:8.0.28
  volumes:
   - ldoc_db:/var/lib/mysql
  ports:
   - 3306:3306
  command: --default-authentication-plugin=mysql_native_password
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DATABASE=logicaldoc
   - MYSQL_USER=ldoc
   - MYSQL_PASSWORD=changeme

 logicaldoc:     
  container_name: logicaldoc
  image: logicaldoc/logicaldoc
  depends_on:
   - db
  command: ["/installer/wait-for-it.sh", "mysql-ld:3306", "-t", "30", "--", "/logicaldoc.sh", "start"]
  ports:
   - 8080:8080
  environment:
   - LDOC_MEMORY=3000
   - LDOC_USERNO=
   - DB_HOST=mysql-ld
   - DB_NAME=logicaldoc
   - DB_USER=ldoc
   - DB_PASSWORD=changeme
   - DB_PORT=3306
  volumes:
   - ldoc_conf:/LogicalDOC/conf
   - ldoc_repository:/LogicalDOC/repository
#  ulimits:
#    nproc: 65535
#    nofile:
#      soft: 6000
#      hard: 40000
#  mem_limit: 7000000000

volumes:
  ldoc_db:
  ldoc_conf:
  ldoc_repository:




