version: "3.1"

services:

  logicaldoc:
    depends_on:
      - mysql-ld
    command: ["/installer/wait-for-it.sh", "mysql-ld:3306", "-t", "30", "--", "/logicaldoc.sh", "start"]       
    image: logicaldoc/logicaldoc
    ports:
      - 8080:8080
    environment:
      - LDOC_MEMORY=2000

  mysql-ld: 
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=logicaldoc
      - MYSQL_USER=ldoc
      - MYSQL_PASSWORD=changeme      

